# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180119_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
