# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room', serialize=False, to='chat.Room')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='feed.Board')),
                ('original_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
